### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jonnyathan** [ospfranco/react-native-link-preview#11]
Attempting to run `npm build` with this package gives the following error: `Failed to minify the code from this file: ./node_modules/react-native-link-preview/index.js:10`

Here are the dependencies in my package.json:
```
"dependencies": {
    "firebase": "^4.3.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-native": "^0.47.1",
    "react-native-link-preview": "^1.2.0"
  },
  "devDependencies": {
    "react-scripts": "1.0.11"
  },
  ```

Happy to provide any extra info you need.

**Comment by ospfranco** [comment]
Could you please show what your `build` do? or if you are using gulp/webpack to minify the code just show how is this being done, thanks!
