### ISSUE TITLE
Fetch images?

### ISSUE THREAD

**Issue by EmilScherdin** [ospfranco/react-native-link-preview#19]
Hi! 

First of, great package. Works like a charm!
One thing I'm missing is fetching image links. It would be nice it the package did this.

Like this one: 
[https://i.imgur.com/lEzmnXr.jpg](https://i.imgur.com/lEzmnXr.jpg)

I would like it because it somehow expected when posting and image in e.g. a feed (where I use this) that it would be fetched. Thoughts?

**Comment by ospfranco** [comment]
the way the package works is by fetching the detected url and looking into the internal html for the properties that are important, I'm not really sure about image fetching however, this seems something you could test with a regex, if it was to be implemented the shape of the response would be the same.

What would be the expected output of https://i.imgur.com/lEzmnXr.jpg?

**Comment by ospfranco** [comment]
Hey, sorry it is a little late, but I really had no time to look into this, I just tested the link your provided and the response I get from the library is:

```{ url: 'https://imgur.com/lEzmnXr',
      title: 'Imgur: The magic of the Internet',
      description: 'Post with 393 views.',
      mediaType: 'article',
      images: [ 'https://i.imgur.com/lEzmnXr.jpg?fb' ],
      videos: [] }```

Seems to me this is working as intended, I think handling more logic to check for bigger sizer images is out of the scope of this library, so I won't be spending more time on this, however if you feel you can solve this in an elegant manner feel free to submit a pull request.
