### ISSUE TITLE
fetch call crashing android

### ISSUE THREAD

**Issue by brycepavey** [ospfranco/react-native-link-preview#2]
Using react-native 0.38 the fetch call seems to be the cause of a crash on Android for certain URLs, ones that point directly to binary files such as images or pdf docs. 

![screen shot 2016-12-12 at 10 07 38 am](https://cloud.githubusercontent.com/assets/6986339/21084140/db394fd2-c052-11e6-9d2d-dddec6d59beb.png)

We attempted replacing this library with the react-native-page-previewer library only to find we received the same crash, after investigating we realised that the crash was coming from react-natives fetch and only occurs when in either release mode or if in debug mode without connecting to remote debugger. 
Here's a URL that crashes when fetching: https://static.mailchimp.com/web/features/mc-features-report.jpg

We've managed to work around this bug by replacing the rn fetch call with react-native-fetch-blob library  

```javascript
if(detectedUrl) {
        RNFetchBlob.fetch('GET', detectedUrl)
        .then(response => response.text())
        .then(text => {
          resolve(this._parseResponse(text, detectedUrl))
        })
        .catch(err =>
          reject(err)
      )
```

**Comment by ospfranco** [comment]
As far as I remember the guys at React broke their own compatibility with the fetch API, a colleague of mine solved this by using a fetch polyfill.

As such this problem is not from the library but rather of the react guys messing up their own product, I suggest you update react to the latest version and see what happens.

**Comment by ospfranco** [comment]
I'm closing this for now, if you find the problem again comment here and I'll re-open it.

**Comment by vspedr** [comment]
Hey @ospfranco, I'm running into the same issue... I found that the `fetch` call is always returning `text/plain` in the Content-Type response header, even though it's a PDF file, image, HTML document or whatever. Requesting from the same URL in a browser, Postman, `axios` or `node-fetch` returns the expected header value.
An example, slightly modifying your `index.js`:

```
if (detectedUrl) {
  fetch(detectedUrl)
  .then(response =>
    console.log(detectedUrl);
    console.warn(response.headers.get('Content-Type'));
```
gives me this:

<img width="458" alt="screen shot 2017-04-04 at 14 54 56" src="https://cloud.githubusercontent.com/assets/9813942/24675994/a0f85030-1957-11e7-87e1-5caa00083fed.png">

[URL](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf
)

Could you please elaborate on your colleague's solution? Neither `axios` or `node-fetch` will work in React Native.

**Comment by ospfranco** [comment]
[whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) o update react to a newer version.

**Comment by 20pro** [comment]
Hi, i have the same problem :) When is the next release of this Library ?

**Comment by ospfranco** [comment]
This was not a problem with the library but rather with react-native, as already stated use a polyfill or update your react-native version.

**Comment by 20pro** [comment]
I'm with react native 0.56. Can you help me please ?

**Comment by gugakatsi** [comment]
@20pro have you found any solution? should i upgrade blob ?
