### ISSUE TITLE
Access Denied on Android

### ISSUE THREAD

**Issue by sujay-bidchat** [ospfranco/react-native-link-preview#20]
## 1. Response on android (WORKS ON IOS):
{
   url: 'https://www.zomato.com',
   title: 'Access Denied',
   description: undefined,
   mediaType: 'website',
   images: [],
   videos: [] 
}

## 2. Even most of the time the 'images' array is empty for valid urls.
     The 'title' field returns correct names but 'images' array is empty.

**Comment by ospfranco** [comment]
Have you added permissions to your android manifest.xml file?

**Comment by sujay-bidchat** [comment]
May I know which permissions?

**Comment by ospfranco** [comment]
https://stackoverflow.com/questions/2169294/how-to-add-manifest-permission-to-android-application

**Comment by sujay-bidchat** [comment]
Internet permission was already added in Android manifest.

**Comment by sujay-bidchat** [comment]
Even sometimes 'https://www.google.com' receives empty 'images' array in response but the 'title' field has correct response i.e 'Google'.

This happens many times both on android & ios

**Comment by ospfranco** [comment]
Sorry I could not reproduce this issue, could it be it has to do with some external factor either in your project or internet connection? firewall or something?

Feel free to submit a pull request if you manage to find the root of the problem and fix it, but it seems I cannot help you

**Comment by sujay-bidchat** [comment]
Please try this on both Android and iOS:
Type 'https://www.myntra.com'
1. Sometimes it shows the preview
2. Most of the times 'No Preview Available'
3. Sometimes preview is shown but the preview goes away automatically and shows 'No Preview Available'

**Comment by ospfranco** [comment]
ok

1) I had to double check the code of the library to make sure I'm not returning a 'no preview available', so the library will never return this, SO: this sounds like the UI representation you have built on top of the library, so possible source of errors might be there, double check your code

2) I have built a simple script to test this, 

```#!/usr/bin/env bash

COUNTER=0
         while [  $COUNTER -lt 100 ]; do
             echo The counter is $COUNTER
             yarn test
             if [ $? -eq 1 ]
             then
              echo 'FAILED TO FETCH'
              exit
             fi
             let COUNTER=COUNTER+1 
         done```

and the test:

```it('should handle image urls', async () => {
    try {
      const info = await LinkPreview.getPreview('https://www.myntra.com');
      // const info = await LinkPreview.getPreview('Not a link');

    } catch (e) {

      expect(e.error).to.be('FORCE FAIL')
    }
  })```

the final output:


```
The counter is 99
yarn run v1.3.2
$ jest --forceExit
 PASS  __tests__/index.spec.js
  link preview
    ✓ should handle image urls (298ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.162s
Ran all test suites.```

it has ran the 100 times and not failed once, so again, this seems to be you doing something wrong on your end, check for firewalls, proxies, your async logic in your app, but I repeat, this cannot be a problem with the library, it is plain and simple javascript code, no android/iOS configuration attached to it.

**Comment by ospfranco** [comment]
just FYI, updated the test to check for JSON content and increased tests to 1000 and still not a single failure.

also, I'm in spain/germany so no government/ISP rate limiting/blocking, don't know where you are, but could also be a possibility.
