### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by everythingspirals** [ospfranco/react-native-link-preview#23]
For some reason when I run this:
`let response = await LinkPreview.getPreview(https://i.imgur.com/LDFO6YV.png);`

I get:
`RangeError: Maximum call stack size exceeded
[0]        at Object.exports.getName (C:\Users\project\packages\server\node_modules\domutils\lib\traversal.js:22:27)`

**Comment by ospfranco** [comment]
Hmm weird, unfortunately I don't have time to check this, does it fail with other sites?
