### ISSUE TITLE
Unknown MIME type for URL

### ISSUE THREAD

**Issue by kaiszybiak** [ospfranco/react-native-link-preview#26]
Hello @ospfranco,
when I run the following code:
`        LinkPreview.getPreview('https://www.macys.com/shop/product/jaywalker-mens-animal-print-jacket?ID=5219568&CategoryID=80617')
            .then(data => console.debug(data));`

I always get the following Promise Rejection. No matter which URL I use or even if its just a string:
`Possible Unhandled Promise Rejection (id: 0):
Object {
  "error": "React-Native-Preview-Link: Unknown MIME type for URL.",
}`

Is there something obvious I'm missing?

**Comment by ospfranco** [comment]
@stevenpal could you check this out? I think it might have to do with the latest merged changes

**Comment by stevenpal** [comment]
Sorry about that. I’m pretty sure it’s an issue with how the headers and content-types of the response are being extracted. I think I may have coded that in a way that’s too specific to a platform (e.g. looking for “_headers”). Won’t be able to take a look until Monday, so if someone wants to take a look in the interim please do.

**Comment by ospfranco** [comment]
@kaiszybiak in the mean time you can revert to using an older version 1.3.1 maybe

**Comment by kaiszybiak** [comment]
@ospfranco @stevenpal Thanks for the quick response.  

> @kaiszybiak in the mean time you can revert to using an older version 1.3.1 maybe

Yes. I will check that.

**Comment by ospfranco** [comment]
New version is out, please check it out
