### ISSUE TITLE
CORB error message

### ISSUE THREAD

**Issue by willysoriaguzman** [ospfranco/react-native-link-preview#32]
Having this error messages:
`Failed to load https://www.youtube.com/watch?v=MejbOFk7H6c: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.youtube.com/watch?v=MejbOFk7H6c with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

Is there a fix or workaround for this?

**Comment by ospfranco** [comment]
Please read the README, this package will never work in CORS protected environments (web browsers)
