### ISSUE TITLE
'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by lc3t35** [ospfranco/react-native-link-preview#33]
With version 1.3.4, when I try to build within Xcode (expo detached mode, react-native link done), I have this error coming from RNReactNativeLinkPreview.h -> #import "RCTBridgeModule.h" -> #import <React/RCTDefines.h>
```
'React/RCTDefines.h' file not found
```
As stated [here](https://docs.expo.io/versions/v29.0.0/expokit/expokit), I have the Header Search Paths set with Pods/Headers/Public/React

**Comment by lc3t35** [comment]
Adding a .podspec file allows to install everything with pod install and solves this issue.

**Comment by ospfranco** [comment]
I'm thinking about removing the native code all together since the library should work without the need for native code/bridging

**Comment by ospfranco** [comment]
v1.3.5 (now on npm) should contain no native code, no need to fiddle with pods and other dependencies.
