### ISSUE TITLE
buildToolsVersion error on Android

### ISSUE THREAD

**Issue by 3luyka** [ospfranco/react-native-link-preview#35]
Hey, could you please update `buildToolsVersion` because I've get an error `The SDK Build Tools revision (23.0.1) is too low for project ':react-native-link-preview'. Minimum required is 25.0.0`

**Comment by ospfranco** [comment]
Hmm I think you should update your build tools anyways, since august google is forcing everyone to target API version 26 when publishing apps on the play store, in any case, closing this since I intend to remove all native code, since the library is a pure js solution.
