### ISSUE TITLE
Installing dependency cheerio-without-node-native breaks the webpack

### ISSUE THREAD

**Issue by mynkgrwl** [ospfranco/react-native-link-preview#4]
Installing dependecy cheerio-without-node-native is breaking the webpack

**Comment by ospfranco** [comment]
Would you please provide more info? is there any error? how did you install this package? the library has it's own dependency tree which should not cause any problems.

**Comment by ospfranco** [comment]
Because of the bad quality of this ticket (no steps to reproduce, no accurate description of the error) and no response from @mynkgrwl, I'm closing this, feel free to re-open if encountered again.
