### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin', On React.js

### ISSUE THREAD

**Issue by usama-asfar** [ospfranco/react-native-link-preview#43]
Full error
`Access to XMLHttpRequest at 'https://www.youtube.com/watch?v=MejbOFk7H6c' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by ospfranco** [comment]
Read the readme
