### ISSUE TITLE
standalone version

### ISSUE THREAD

**Issue by Kikobeats** [ospfranco/react-native-link-preview#6]
Could be possible use it as a standalone function?

**Comment by ospfranco** [comment]
I'm sorry, I don't understand the problem? what do you mean as a standalone function?

**Comment by Kikobeats** [comment]
yes, out of react component

**Comment by ospfranco** [comment]
can you give a code example of how would you use this?

**Comment by ospfranco** [comment]
I don't really understand what is the problem here, creating a react component to use this makes no sense, this is meant only for retrieving page information how it is displayed is up to each developer that uses it. 

Closing this
