### ISSUE TITLE
get better titles for facebook pages

### ISSUE THREAD

**Issue by uriva** [ospfranco/react-native-link-preview#8]
Hi,
Whenever I'm inputting a fb page I'm getting "Comments" as the title.
Can this be improved somehow?

**Comment by ospfranco** [comment]
This seems to be a very specific use case, unfortunately I don't have the time to take a look into it right now, however feel free to take a look at the code and submit your own pull request.

**Comment by uriva** [comment]
Cool, I think I will.
It's going to be non-elegant and specific code but still it's probably accounts for more than 50% of the links people share.

**Comment by uriva** [comment]
Ok turns out it's easier than I thought. Sent you a proposal.

**Comment by ospfranco** [comment]
Fixed by: https://github.com/ospfranco/react-native-link-preview/pull/9

**Comment by uriva** [comment]
@ospfranco not available yet on npm - increment the version maybe?

**Comment by ospfranco** [comment]
just published, my bad, version 1.1.2
